### PR TITLE
style, ref(app): 12127, 12144 - panels grid layout

### PR DESCRIPTION
**Pull request by IlyaIzr**
width -1920px
image
width - 1440px
image
width - mobile
image

### CODE REVIEW

**Comment by Komzpa** [comment]
Screenshots LGTM. Please check:
  - folded panel has same width as unfolded one
  - on mobile the disaster shape is fit in between the buttons and not under them

**Comment by propakov** [comment]
boxshadow is different 
Screenshot 2022-09-22 at 17 18 02

**Comment by propakov** [comment]
@IlyaIzr I'm on mac screen 16 and all panels on one side. 
Looks like something expected for 1440px 
Screenshot 2022-09-22 at 17 37 37

**Comment by propakov** [comment]
scroll is broken when panel is minimized (you can't see bottom of the list)
medium position scroll
image
bottom position scroll
Screenshot 2022-09-22 at 17 44 57

**Comment by IlyaIzr** [comment]
> Looks like something expected for 1440px

for now it's better to have 1920px+ design, mobile design, and the middle-laptop design, it's not strictly <1440px. I think

**Review by propakov — COMMENTED** [review]
Code LGTM but need to fix scroll issues

**Comment by propakov** [comment]
oh, Layers panel still collapses in case of other panels opened
Screenshot 2022-09-23 at 14 01 16

**Review by propakov — APPROVED** [review]

**Pull request merged**
