### PR TITLE
feat(i18n): 12862 - gettext format support on frontend side added

### PR DESCRIPTION
**Pull request by propakov**
https://kontur.fibery.io/Tasks/Task/Add-gettext-format-support-on-frontend-side-12862

Screenshot 2022-11-11 at 10 17 06

### CODE REVIEW

**Comment by vkozio** [comment]
As you remember we discussed

> i18n: i18n.t(variable) - avoid, gettext tools expect i18n.t("text…")

And after discussion with @Akiyamka looks like it should be fixed because extractors may be used. You can find problematic places searching for ` i18n\.t\(\w`

**Comment by Komzpa** [comment]
.pot file is usually put into `template` folder nearby the translations, not one level up - as project grows bigger there are sometimes file hierarchies under each of the folders.

**Comment by propakov** [comment]
> As you remember we discussed
> 
> > i18n: i18n.t(variable) - avoid, gettext tools expect i18n.t("text…")
> 
> And after discussion with @Akiyamka looks like it should be fixed because extractors may be used. You can find problematic places searching for ` i18n\.t\(\w`

@vkozio Yep, we have next ticket about extracting translations, so we gonna fix it there
This one is about convertion to gettext and back.

**Comment by propakov** [comment]
@Komzpa wow, nice catch! thanks!

**Review by vkozio — APPROVED** [review]

**Review by Komzpa — APPROVED** [review]
LGTM. I expect we will have another pass on this when actually will have exchange with the translators.

**Pull request merged**
