### PR TITLE
feat(event_list): 11710, 11729 - unify disasters panel and move it under analytics panel

### PR DESCRIPTION
**Pull request by IlyaIzr**
image
image
image

### CODE REVIEW

**Review by Komzpa — CHANGES_REQUESTED** [review]
Issues on screenshot:
 - logo is covered, panel likely higher than screen:
image

 - Analytics panel has no icon

**Comment by IlyaIzr** [comment]
> * logo is covered, panel likely higher than screen:

Will be fixed in the next commit for panels layout

**Comment by IlyaIzr** [comment]
Fix for Kontur logo also delivered
image
image

**Review by Komzpa — APPROVED** [review]
screenshots LGTM

**Comment by propakov** [comment]
loader is a bit not on the center 
image

**Comment by propakov** [comment]
also I found on mobile view (z-index problems, close  panel btn unavailable)
not sure if it is in scope of this ticket or not, maybe more suitable to create bugs
image
image

**Review by propakov — APPROVED** [review]
from code side LGTM, please consider these 2 moments I've found

**Pull request merged**
