### PR TITLE
change default maxzoom for a raster layer from 22 to 24

### PR DESCRIPTION
**Pull request by kalenikaliaksandr**
I have a problem that 22 zoom is not enough for mosaic layer and currently there is no way to specify min and max zooms for layers coming from layers-api. Can we just set it to 25 for now?

### CODE REVIEW

**Comment by IlyaIzr** [comment]
Top maxzoom value is `22` for mapbox https://docs.mapbox.com/help/glossary/zoom-level/
Did you try to run this settings locally?
I'm not sure they will fix anything

**Comment by kalenikaliaksandr** [comment]
@IlyaIzr https://docs.mapbox.com/help/glossary/zoom-level/ seems to be documentation for mapbox basemap rather than mapbox-gl. I have working page that uses mapbox-gl and displays tiles until 24 zoom. I attached screenshot where you can see successful requests to tiles on 23 zoom level for example. https://dev-raster-tiler.k8s-01.konturlabs.com/mosaic_viewer
Screenshot from 2022-10-20 15-56-27

**Review by IlyaIzr — APPROVED** [review]
I say we can try it if it's not breaking anything

**Comment by kalenikaliaksandr** [comment]
from errors in console I learned that actual max valid zoom is 24.
Screenshot from 2022-10-20 17-13-39

**Pull request merged**
